version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns: ["org.junit*", "org.assertj*", "org.testfx*", "org.hamcrest*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
