package io.hl7sender.core.tls;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.hl7sender.core.listener.ListenerSettings;
import io.hl7sender.core.listener.TestListener;
import io.hl7sender.core.mllp.MllpClient;
import io.hl7sender.core.mllp.MllpClientConfig;
import io.hl7sender.core.send.Hl7Sender;
import io.hl7sender.core.send.SendOptions;
import io.hl7sender.core.send.SendOutcome;
import io.hl7sender.core.send.SendResult;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.List;
import javax.net.ssl.SSLContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;

/** MLLP over TLS and mutual TLS, with real certificates generated by keytool. */
@Timeout(60)
class TlsTest {

    static final String MESSAGE = "MSH|^~\\&|APP|FAC|RAPP|RFAC|20260101||ADT^A01^ADT_A01|C1|P|2.5.1\r"
            + "EVN|A01|20260101\rPID|1||MRN1^^^H^MR||DOE^JANE\rPV1|1|I\r";
    private static final char[] PW = TestCertificates.PASSWORD.toCharArray();

    @TempDir
    static Path certDir;
    static TestCertificates certs;

    private final Hl7Sender sender = new Hl7Sender();
    private TestListener listener;

    @BeforeAll
    static void generateCertificates() throws Exception {
        certs = new TestCertificates(certDir);
    }

    @AfterEach
    void stop() {
        if (listener != null) {
            listener.close();
        }
    }

    private int startTlsListener(Path serverKeyStore, String trustedClients, boolean requireClientCert)
            throws IOException {
        SSLContext ctx = TlsContexts.server(serverKeyStore, PW, trustedClients, null);
        listener = new TestListener("127.0.0.1", 0, ListenerSettings.DEFAULTS, m -> { }).useTls(ctx, requireClientCert);
        listener.start();
        return listener.port();
    }

    private SendResult send(int port, TlsSettings tls, char[] keyPw) throws IOException {
        TlsOptions options = TlsContexts.client(tls, null, keyPw);
        return sender.send(MllpClientConfig.of("127.0.0.1", port).withTimeouts(3000, 3000), options, MESSAGE,
                SendOptions.DEFAULTS);
    }

    private static TlsSettings trusting(Path cert) {
        return new TlsSettings(true, cert.toString(), "", true, TlsSettings.DEFAULT_PROTOCOLS);
    }

    @Test
    void sendsOverTlsToATrustedServer() throws Exception {
        int port = startTlsListener(certs.serverKeyStore, "", false);
        SendResult r = send(port, trusting(certs.serverCert), null);
        assertThat(r.outcome()).isEqualTo(SendOutcome.ACCEPTED);

        TlsOptions options = TlsContexts.client(trusting(certs.serverCert), null, null);
        try (MllpClient client = new MllpClient(MllpClientConfig.of("127.0.0.1", port), options)) {
            client.connect();
            assertThat(client.isTls()).isTrue();
            assertThat(client.peerCertificates()).isNotEmpty();
            assertThat(client.peerCertificates().get(0).getSubjectX500Principal().getName()).isEqualTo("CN=localhost");
        }
    }

    @Test
    void untrustedServerIsRejected() throws Exception {
        int port = startTlsListener(certs.serverKeyStore, "", false);
        SendResult r = send(port, new TlsSettings(true, "", "", true, TlsSettings.DEFAULT_PROTOCOLS), null);
        assertThat(r.outcome()).isEqualTo(SendOutcome.CONNECTION_FAILED);
        assertThat(r.detail()).startsWith("TLS handshake failed");
    }

    @Test
    void hostnameIsVerifiedUnlessDisabled() throws Exception {
        int port = startTlsListener(certs.wrongHostKeyStore, "", false);
        SendResult strict = send(port, trusting(certs.wrongHostCert), null);
        assertThat(strict.outcome()).isEqualTo(SendOutcome.CONNECTION_FAILED);
        assertThat(strict.detail()).contains("TLS handshake failed");

        TlsSettings lax = new TlsSettings(true, certs.wrongHostCert.toString(), "", false,
                TlsSettings.DEFAULT_PROTOCOLS);
        assertThat(send(port, lax, null).outcome()).isEqualTo(SendOutcome.ACCEPTED);
    }

    @Test
    void mutualTlsRequiresAClientCertificate() throws Exception {
        int port = startTlsListener(certs.serverKeyStore, certs.clientCert.toString(), true);
        SendResult without = send(port, trusting(certs.serverCert), null);
        assertThat(without.outcome().severity()).isNotEqualTo(SendOutcome.Severity.SUCCESS);

        TlsSettings mutual = new TlsSettings(true, certs.serverCert.toString(), certs.clientKeyStore.toString(), true,
                TlsSettings.DEFAULT_PROTOCOLS);
        assertThat(send(port, mutual, PW).outcome()).isEqualTo(SendOutcome.ACCEPTED);
    }

    @Test
    void protocolsCanBePinned() throws Exception {
        int port = startTlsListener(certs.serverKeyStore, "", false);
        TlsSettings tls12 = new TlsSettings(true, certs.serverCert.toString(), "", true, "TLSv1.2");
        assertThat(send(port, tls12, null).outcome()).isEqualTo(SendOutcome.ACCEPTED);
        TlsSettings bogus = new TlsSettings(true, certs.serverCert.toString(), "", true, "SSLv2");
        SendResult r = send(port, bogus, null);
        assertThat(r.outcome()).isEqualTo(SendOutcome.CONNECTION_FAILED);
        assertThat(r.detail()).contains("None of the configured TLS protocols");
    }

    @Test
    void inspectsCertificatesAndWarnsBeforeExpiry() throws Exception {
        Clock now = Clock.systemUTC();
        List<CertificateInfo> server = TlsContexts.inspect(certs.serverKeyStore, PW, "Client certificate");
        assertThat(server).singleElement().satisfies(c -> {
            assertThat(c.subject()).isEqualTo("CN=localhost");
            assertThat(c.status(now)).isEqualTo(CertificateInfo.Status.VALID);
            assertThat(c.warning(now)).isEmpty();
        });
        CertificateInfo soon = TlsContexts.inspect(certs.expiringCert, null, "Trusted").get(0);
        assertThat(soon.status(now)).isEqualTo(CertificateInfo.Status.EXPIRING_SOON);
        assertThat(soon.warning(now)).contains("CN=soon-expiring").contains("expires in");
        assertThat(soon.status(Clock.offset(now, java.time.Duration.ofDays(11))))
                .isEqualTo(CertificateInfo.Status.EXPIRED);
    }

    @Test
    void badStoresGiveClearErrors() throws Exception {
        assertThatThrownBy(() -> TlsContexts.load(certs.serverKeyStore, "wrong".toCharArray()))
                .isInstanceOf(IOException.class).hasMessageContaining("wrong password");
        assertThatThrownBy(() -> TlsContexts.load(certDir.resolve("missing.p12"), PW))
                .isInstanceOf(IOException.class).hasMessageContaining("not found");
        Path junk = Files.writeString(certDir.resolve("junk.pem"), "not a cert");
        assertThatThrownBy(() -> TlsContexts.load(junk, null)).isInstanceOf(IOException.class);
        TlsSettings pemKey = new TlsSettings(true, "", certs.clientCert.toString(), true, "TLSv1.3");
        assertThatThrownBy(() -> TlsContexts.client(pemKey, null, null))
                .isInstanceOf(IOException.class).hasMessageContaining("PKCS12 or JKS");
    }
}
